### ISSUE TITLE
Twitter is not working anymore

### ISSUE THREAD

**Issue by pellea** [wasteam/waslibs#1]
Hello,

Twitter calls are not working anymore. Actually the result seems to be returned with a gzip compression.

To solve this, I changed HttpWebRequest to HttpClient in the TwitterDataProvider.cs file.

```c#

internal class OAuthRequest
    {
        public async Task<string> ExecuteAsync(Uri requestUri, TwitterOAuthTokens tokens)
        {
            var requestBuilder = new OAuthRequestBuilder(requestUri, tokens);
            HttpClient client = new HttpClient(new HttpClientHandler { AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip });
            client.DefaultRequestHeaders.Authorization = AuthenticationHeaderValue.Parse(requestBuilder.AuthorizationHeader);

            return await client.GetStringAsync(requestBuilder.EncodedRequestUri);
        }
    }

```

Regards,
Adrien.

**Comment by javitosanchez** [comment]
Thanks Adrien,

Maybe you could create a pull request with your solution. Once we test it we will include into the master branch to release a version with the fix.

**Comment by javitosanchez** [comment]
Finally we have implemented a fix with GZipStream class in order to avoid the complexity of cross platform dependencies between 8.1 and 10.

Thanks Adrien for your interest.We hope you to keep involved in waslibs.
