### ISSUE TITLE
SectionListItem

### ISSUE THREAD

**Issue by Arthur-Lee** [wasteam/waslibs#12]
why the SectionListItem always show an error that " cannot create an instance of Ilist" in the Blend? but there is no error in the runtime. Is there any solution to solve it?  it is very annoying!!

**Comment by javitosanchez** [comment]
Thanks for reporting this. We are working on a solution. Have you detected any other problem in the designer?

**Comment by Arthur-Lee** [comment]
thank for your repay, there maybe be a little suggestion about the window10New app. DetailViewModel page has a MouseMoved event to control RestoreFullButton. it maybe to need a more "universal way" to do such as PointerMove. although I don't test whether a tap or stylus move can show the RestoreFullButton.

**Comment by javitosanchez** [comment]
Solved in the current version
