### ISSUE TITLE
Youtube player

### ISSUE THREAD

**Issue by IgorGiga** [wasteam/waslibs#15]
At the moment Youtube player in your apps is actually an embed html fragment... Is there a chance that you can somehow update this player to MEET that in Movies&TV app in W10? That would be GAME CHANGER for me personally! This current player is very bad, especially with those extremely small buttons and other stuff... Please, answer me!

**Comment by javitosanchez** [comment]
Igor,
YouTube does not provide the video url in it's API. That's why we are using the YouTube embedded player. At the moment we haven't see any other option.

**Comment by IgorGiga** [comment]
OK! Thank you for an answer!
