### ISSUE TITLE
ResponsiveGridView have no Items

### ISSUE THREAD

**Issue by adamkalicinscy** [wasteam/waslibs#16]
Hi,

I'm using a ResponsiveGridView and it works great when i download it from nuget (version 1.0.4). Unfortunately, there is no header property. So I downloaded the code from here and built with the build.bat. I made reference in my project to AppStudio.Uwp.dll and it turned out that the list is empty. What am I doing wrong? There is no compilation errors, and yet nothing has been changed.

**Comment by javitosanchez** [comment]
I'm not sure what's happening. I recommend you to include the Windows.AppStudio.Uwp project on your solution, remove the reference in the project.json and add "project reference" from your client project to Windows.AppStudio.Uwp project. This way you will be sure to target the right reference.

**Comment by javitosanchez** [comment]
Closing this due to non response.
