### ISSUE TITLE
PageTokens in Youtube Datasource

### ISSUE THREAD

**Issue by IgorGiga** [wasteam/waslibs#17]
This is REALLY necessary! I hope this feature will come soon! Do you have it in your plans at least?

**Comment by javitosanchez** [comment]
Igor, could be more precise? It's about pagination?

**Comment by IgorGiga** [comment]
Yes! Pagination! So that we could finally load all videos from playlists!

**Comment by IgorGiga** [comment]
This is how I would like this thing to work... I would like to make an app in App Studio for my favorite tv show by pulling out all the episodes from Youtube and sorting them into playlists by season... In that way I will have five playlists by around 150 videos each, but that I just cannot accomplish via App Studio till this date... There is that number limit in how much videos I can pull from Youtube playlist... You have recently boosted it up to 40, but that is not enough... Thank for that btw, it was my feature request! BUT NOW PLEASE ADD PAGE TOKENS FOR YOUTUBE, SO I CAN FINALLY START WORKING ON MY APP AGAIN! I think you should have been added this feature right at the beggining, but situation is what it is... To explain this more further... In order to show 150 videos today, I would need four separate playlists, but we can accomplish this with just one playlist quite easily if you implement these page tokens! It should look like this in reality: I have a playlist with like 200 videos, but App Studio should manage it in this way - it first loads 40 videos, and then when user scroll to the bottom of that list, app automatically loads the next 40 videos and then again and again! You repeat this CONTINUOUSLY until we load all those videos! THIS IS THE WAY HOW ALL THOSE THIRD-PARTY YOUTUBE APPS IN WIN STORE WORK! So I hope you can bring this idea into the reality in one of next updates! All App Studio users will be very grateful if you implement this, but I will be the most! 

Sorry for long text! All the best to App Studio team! Keep up an amazing work! See you! Regards!

**Comment by javitosanchez** [comment]
Thanks for your explanation. You have to realize that we have to get the common factor from all the data providers we have...
We are designing a solution that covers all our data providers.

We'll keep you updated.

**Comment by IgorGiga** [comment]
@javitosanchez  Any progress on the issue? Will this come soon? Cannot wait anymore... ;)

**Comment by javitosanchez** [comment]
@IgorGiga we have a preliminar version developed in [dev ](https://github.com/wasteam/waslibs/tree/DEV)branch. You can start playing with it!

**Comment by IgorGiga** [comment]
Fantastic! Thanks!

**Comment by javitosanchez** [comment]
Released in the current version

**Comment by IgorGiga** [comment]
Thank you guys!!!
