### ISSUE TITLE
More than 50 videos for Youtube

### ISSUE THREAD

**Issue by yeejmeem** [wasteam/waslibs#20]
Hi Windows App Studio Team
We want more than 50 videos for youtube. Please add pagetoken, if we have more than 50 videos, appstudio can't get all videos in playlist. Appstudio first version for windows phone can get all list videos. We suggets give it come back.
Love!

**Comment by IgorGiga** [comment]
@yeejmeem Hi! Maybe you haven't noticed, but I have already suggested this feature a few months ago in another issue. Nevertheless, I totally give it my support here too. WE NEED THIS!!!

**Comment by javitosanchez** [comment]
We are working right now on this. Stay tuned!

**Comment by IgorGiga** [comment]
@javitosanchez Awesome!

**Comment by yeejmeem** [comment]
@javitosanchez Awesome! We need it, we are waiting your update.

**Comment by benjimoola** [comment]
Hello team, Please could you guys teach me how to implement my own data provider with the singleton pattern? i have spent days studying the design pattern but i just cant rap my head around how requests are made. please show me and example implementing a none Json or XML feed site. lets use IMDB or Rotten tomatoes for example. that's in advance.

**Comment by javitosanchez** [comment]
Hi @benjimoola,
If you want to create your own DataProvider you have to inherit from `DataProviderBase<TConfig, TSchema>` and implement the required abstract methods. To do that, first you need to implement your schema (`TSchema`) that defines the data returned by the DataProvider. Also you need to implement the configuration required to extract your data (`TConfig`). And lastly you have to implement the default parser that converts from a raw string to a collection of your schema objects. If the data format if json, you can use the `JsonParser<T>` class in the `AppStudio.DataProviders.Core` namespace.

Example:


```
    public class MyDataProvider : DataProviderBase<MyConfig, MySchema>
    {
        protected override async Task<IEnumerable<TSchema>> GetDataAsync<TSchema>(MyConfig config, int maxRecords, IParser<TSchema> parser)
        {
            //TODO: GET DATA FROM DATASOURCE IN ASYNC WAY
            string data = null;
            await Task.Run(() => {
                data = "";
            });

            return parser.Parse(data);
        }

        protected override IParser<MySchema> GetDefaultParserInternal(MyConfig config)
        {
            return new MyParser();
        }

        protected override void ValidateConfig(MyConfig config)
        {
            //TODO: VALIDATE CONFIG
        }
    }

    public class MySchema : SchemaBase
    {
        //TODO: IMPLEMENT YOUR OWN SCHEMA
    }

    public class MyConfig
    {
        //TODO: IMPLEMENT THE REQUIRED CONFIG FOR YOUR DATA PROVIDER
    }

    public class MyParser : IParser<MySchema>
    {
        public IEnumerable<MySchema> Parse(string data)
        {
            //TODO: IMPLEMENT YOUR PARSER
            throw new NotImplementedException();
        }
    }
```

**Comment by benjimoola** [comment]
I have done it in a different way because i am not getting my data from some kind of Restful API. I need to understand one more thing though. Lets say you are using a flipview or the Carousel control in SectionListPage. How do you Navigate to a DetailPage and a ListPage. The code below does not seem to work when i click the item with the binding commandcontrols:ItemClickCommand.Command="{Binding NavComand}"

`public ICommand NavCommand
        {
            get
            {
                return new RelayCommand(() =>
                {
                    NavigationService.NavigateToPage("BookDetailPage");

                });
            }
        }`

**Comment by javitosanchez** [comment]
Not sure if I understand your question. Could you be more precise? Or attach a code snippet?

**Comment by benjimoola** [comment]
Ok. lets look at it this way... You are using the section lists template provided in the sample app and you went along and added some flipview controls as well as Carousel, You want to Navigate to Detail page of the selected Item when someone clicks an Item in Carousel or FlipView, How do you do it? 

How do you make the HeaderLinkClickCommand work as well when someone clicks on view all so they can view all the content in a particular section.

my FLipView implementation looks like this. 
`<FlipView x:Name="FeatureHub" Height="300"
                             SelectedItem="{Binding ItemClickCommand}"
                              UseTouchAnimationsForAllNavigation="True" 
                              ItemsSource="{Binding FeaturedItems}"
                              ItemTemplate="{Binding ItemTemplate}"
                              >
                            <interactivity:Interaction.Behaviors>
                                <behave:SelectorAutoScrollBehavior />
                            </interactivity:Interaction.Behaviors>
                        </FlipView>`

`public ICommand ItemClickCommand
        {
            get
            {
                return new RelayCommand(() =>
                {
                    NavigationService.NavigateToPage("Carousel");
                });
            }
        }`

**Comment by javitosanchez** [comment]
You are talking about 2 different scenarios:
**If you want to navigate from a Carousel**: This control exposes a "command" property: **ItemClickCommand** that is invoked when the user clicks an item. When the command is invoked it passed the target clicked item that is binded (the ViewModel). Here you can navigate as you want:
```
        public RelayCommand<ItemViewModel> ItemClickCommand
        {
            get
            {
                return new RelayCommand<ItemViewModel>(
                (item) =>
                {
                    NavigationService.NavigateToPage("TargetPage", item);
                });
            }
        }
```
**If you want to navigate from a FlipView**: This control doesn't expose any event or command for this. And the ItemClickCommand shouldn't work, because it needs the control inherits from ListViewBase. This is because the command listen for the ItemClick event:

```
        private static void OnCommandPropertyChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
        {
            var control = dependencyObject as ListViewBase;
            if (control != null)
            {
                control.ItemClick += OnItemClick;
            }
        }
```
If you need to navigate from a FlipView you should listen for a Tapped event in the container of each item an do the navigation with the **SelectedItem** property. Or include some kind of button in each item. But anyway you have to implement it yourself.

**Comment by benjimoola** [comment]
I really appreciate the time you take to respond to me. I have dully understood the singleton pattern for data. let me do some navigation. :)

**Comment by benjimoola** [comment]
Think the design pattern that uses itemviewmodel is different from the design pattern of this template. What I mean is that the design pattern with DJNano is different from this one. When I do the itemclick command I get a weird exception which says my dataprovider class cannot be converted to the page am trying to navigate to. 

I would have loved to use djNano templates but most of the codes are in the DLL files from nugget package.

I have understood every aspect of this sample except for the navigation. 
Please could you show me an example that will navigate from Flickr page to another page? e.g Facebook page? :)

**Comment by benjimoola** [comment]
Finally I did it... 
` public RelayCommand<object> ItemClickCommand
        {
            get
            {
                return new RelayCommand<object>(
                (i) =>
                {
                    NavigationService.NavigateToPage(typeof(FacebookPage));
                });
            }
        }`

and remove the app studio.common lib and reference app studio.uwp


I have done this long ago not know the main probe was the namespace app studio.common.

**Comment by javitosanchez** [comment]
Released in the current version
