### ISSUE TITLE
How to add formatting option in HtmlViewer provided in this library?

### ISSUE THREAD

**Issue by kinju4374** [wasteam/waslibs#21]
I came across this API and I am using HTML Viewer. I am displaying HTML using it and now I want to allow user to edit (i.e format data) is it possible to achieve using this library?

**Comment by javitosanchez** [comment]
The HtmlViewer control was designed to render/display html data only and apply simple styles formatting. 

However, it's based on WebView control. Maybe this control could adjust better in you are trying to do.

By the way, in our DEV branch, we are working in a new control [HtmlBlock ](https://github.com/wasteam/waslibs/tree/DEV/src/AppStudio.Uwp/Controls/HtmlBlock) for html rendering not based on WebView. It works much more better for html rendering...

**Comment by kinju4374** [comment]
Thanks.

So, you are suggesting that I can use HtmlViewer to allow simple formatting options? Could you provide some sample links from where I can learn to add formatting options in HtmlViewer?

Also, can I use HtmlBlock right now in my project to achieve my requirement?

**Comment by javitosanchez** [comment]
The HtmlViewer control only allows you to customize the foreground color, background color and font size. On the other hand, HtmlBlock allows you to apply styles to each of the html tags supported.

If you cannot wait until our next release, you can fork/clone, checkout the DEV branch and add the project to your solution (remember remove the reference to nugget).

You can also run the sample app from DEV branch and see how HtmlBlock control works. 

One important thing is HtmlBlock is under development, so you could find a few bugs...

**Comment by kinju4374** [comment]
Thanks @javitosanchez  I need to allow the user to customize any word to bold,italic,underline. Add bullet list, add number list, change heading styles , change foreground colors.

So, as you said I think for this, HtmlBlock will be useful right?

**Comment by javitosanchez** [comment]
Right!

**Comment by kinju4374** [comment]
Thanks a lot.

Hope Microsoft keep adding useful controls like HtmlBlock in future to its SDK.

**Comment by kinju4374** [comment]
Hi, when you will release HtmlBlock control for this API?

**Comment by javitosanchez** [comment]
We are planning to merge to master branch next week and then release the first beta of 1.5 version. We will keep you updated.

**Comment by kinju4374** [comment]
Ok thanks. I require this control as there is not HTMLEditor available in Windows.

**Comment by kinju4374** [comment]
hi, I checked the Dev project, in HTMLBlock it just displayed content. What I need to do, if I add a button in App bar for example B for Bold, and when the user clicks on that the selected word or sentence must be changed to Bold?

**Comment by kinju4374** [comment]
Please also check **Carousel Control**. It shows which image is selected in Indicator in Desktop App but not in Mobile app. I downloaded mobile app from Windows Store.

**Comment by javitosanchez** [comment]
Hi, you can assign a specific style to each supported html tag in `HtmlBlock` control, and you can do it in runtime. The control has a `DocumentStyle` property composed by a lot of properties (one for each tag). You can change those with styles or directly in c# (all or 1 specific). Please, review the [sample page](https://github.com/wasteam/waslibs/blob/master/samples/AppStudio.Uwp.Samples/Pages/HtmlBlock/HtmlBlockPage.xaml.cs) where there is a combo changing the styles in runtime.

From the carousel control, we are preparing a new release. It should be solved in this one. Thanks for alert us.

**Comment by kinju4374** [comment]
Ok thanks. So, if I select any word then I can change that to Bold or any other HTML format right?

Also,please update when you release the new version in Nuget. These are really helpful controls for any Windows Developer. Thanks for them.

**Comment by javitosanchez** [comment]
Not really. You can assign styles to tag elements. For example, you can change the font color of all `bold` elements in the document (in design time and runtime), but you cannot apply styles to a particular word.

Yesterday we merged to master branch, and also we released a [beta version](https://www.nuget.org/packages/WindowsAppStudio.Uwp/1.4.0-beta0) in Nuget.

**Comment by kinju4374** [comment]
Hi, Thanks for the beta version. I was using Carousel control with the indicator but the indicator is not displaying. My XAML and C# code are below

**XAML Code**

`<StackPanel Grid.Row="1">
            <appStudio:Carousel
                x:Name="evidenceFlipView"
                ItemsSource="{Binding}"
                ContentTemplate="{StaticResource MobileEvidenceFilpViewDataTemplate}"
                MaxItems="1"
                Height="500"
                Margin="5"
                AspectRatio="1.5"
                AlignmentX="Center"
                GradientOpacity="0.3"/>
            <appStudio:Indicator x:Name="indicator" 
                                 Margin="0,9"
                                 ItemsSource="{Binding ItemsSource, ElementName=evidenceFlipView, Mode=TwoWay}"
                                 SelectedIndex="{Binding SelectedIndex, ElementName=evidenceFlipView, Mode=TwoWay}"
                                 ShapeMode="Ellipse" Background="WhiteSmoke" SelectedBackground="DimGray" PressedBackground="Gray" />
        </StackPanel>`

**C# Code**

`evidenceFlipView.ItemsSource = fileList;`

Can you suggest what I have missed?

**Comment by kinju4374** [comment]
If I remove Height from Carousel then it works.

**Comment by javitosanchez** [comment]
Thanks for reporting this. We'd fix it and should be solved in the current version.

**Comment by javitosanchez** [comment]
Released in the current version
