### ISSUE TITLE
[Question] Applying custom CSS to HtmlViewer?

### ISSUE THREAD

**Issue by jlnostr** [wasteam/waslibs#25]
I'm not a fan of the default CSS. But there's no option to add some CSS rules to the generated html. I tried to attach them in my html string using a `<style></style>` container. But the rules in it won't be applied because it's deleted by the JavaScript. Is there a hidden feature to add custom CSS rules?

**Comment by javitosanchez** [comment]
Please read this thread #21

**Comment by javitosanchez** [comment]
Duplicated with #21
