### ISSUE TITLE
How to use VariableSizedGridPanel

### ISSUE THREAD

**Issue by Rivolvan** [wasteam/waslibs#26]
I browsed the available controls in this package and I saw VariableSizedGridPanel. Can I use this on its own? I want to use this for adaptive layout but I am not making a GridView. I tried using this panel but I just saw nothing inside it.

**Comment by javitosanchez** [comment]
The control you are looking for is [VariableSizedGrid](https://github.com/wasteam/waslibs/tree/master/src/AppStudio.Uwp/Controls/VariableSizedGrid). You can see how to use it in the [main page ](https://github.com/wasteam/waslibs/blob/master/samples/AppStudio.Uwp.Samples/MainPage.xaml)of the samples app.
