### ISSUE TITLE
Main page view

### ISSUE THREAD

**Issue by IgorGiga** [wasteam/waslibs#29]
Hi guys! I have one suggestion...

Can you PLEASE add an option that we can set a specific datasource page as the main page of the app, and not to keep it as some kind of "collection" of all of the pages in the app as it is now??? We really need this! Hope you understand what i mean. Thanks!

**Comment by javitosanchez** [comment]
Maybe, you need to specify which items do you want to appear in you home page and not the first ones, right?

This is not related to this components, is more related to [Windows App Studio](http://appstudio.windows.com) generated code. I would suggest you to create a request in [User Voice](https://wpdev.uservoice.com/forums/216486)

**Comment by IgorGiga** [comment]
Not sure you understand me. If I make like five different data source pages in my WAS app, I do want to explicit SET on of them as full main page! Not like the current model,where we can show only few items from each data source pages in the main page!

**Comment by javitosanchez** [comment]
@IgorGiga, please open a suggestion in the [User Voice](https://wpdev.uservoice.com/forums/216486) and we will analyze your request. Thanks!!
