### ISSUE TITLE
#question x64 build on appstudio.windows.com

### ISSUE THREAD

**Issue by k0st1x** [wasteam/waslibs#32]
Just a small question : )

The site appstudio.windows.com generates packages for ARM and x64 platforms.
I am wondering that generating x64 package is not big deal for you guys.
This is just a curiosity.
Are there any potential problems with the generation of x64 assemblies?

**Comment by javitosanchez** [comment]
It shouldn't be any problems with x64 packages. We are not generating this because of storage space saving.
