### ISSUE TITLE
'ImageEx' does not contain a definition for 'ImageFailed'

### ISSUE THREAD

**Issue by darshanrampatel** [wasteam/waslibs#40]
This has changed in Version 1.5.0 - looks to have been as a result of commit: https://github.com/wasteam/waslibs/commit/49ab82ef17179bf5b1ad30209872fe8662f81ceb

If you set the Source of an ImageEx control to a Uri that doesn't exist, you don't get an exception, but nothing is displayed.

How can you use an ImageFailed function with the ImageEx control?

**Comment by javitosanchez** [comment]
The ImageFailed event has been included in DEV branch ([commit](https://github.com/wasteam/waslibs/commit/82d2dce0ac3b6034d8d0ce47626905b48c85c730)). It will be merged in our next release.

**Comment by darshanrampatel** [comment]
Closing this as no longer relevant (using [the Windows Community Toolkit](https://github.com/Microsoft/WindowsCommunityToolkit) now).
