### ISSUE TITLE
Apostrophe and quot didn't render correctly in HtmlBlock

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [wasteam/waslibs#45]
![apostrophy](https://cloud.githubusercontent.com/assets/9501081/18087004/8101d606-6ee5-11e6-9232-acacbc3d194c.PNG)
![quot](https://cloud.githubusercontent.com/assets/9501081/18087013/8b4f4ddc-6ee5-11e6-8fcb-50c6687385a8.PNG)

my app needs to display youtube comments, and youtube api offers two formats (plain text & HTML).. I request html format from the API and I tried to bind those comments in HTML block, but it turned out that the control is not very happy with us.. It rendered perfectly in some place and won't in some other place..

**Comment by javitosanchez** [comment]
Could you attach a repro with content working and content not working?

**Comment by Hanzalah-Adalan** [comment]
# Working
==================================================================
1- `I didn&#39;t make it to the end, my iPad died<br /><br />`
![working 1](https://cloud.githubusercontent.com/assets/9501081/18132069/c8861eaa-6fc7-11e6-815b-aa9e01879d92.PNG)
2- `Video starts at <a href="http://www.youtube.com/watch?v=tPEE9ZwTmy0&amp;t=0m02s">0:02</a> thank me later﻿`
![working 2](https://cloud.githubusercontent.com/assets/9501081/18132080/d268159a-6fc7-11e6-8cc6-e7ed9b1d633a.PNG)
3- `Day 9:<br /><br />I&#39;ve been watching this video over and over again for 216 hours straight now, each time I try to walk away from my computer desk, the same guitar tone is constantly playing by every steps I take. I&#39;ve decided to check outside my window, all I saw was that cat who was in my neighbor&#39;s garden, but this time he was a bit closer to my house, he had the same expression of joy and surprise on his face, but it was getting on me.<br /><br />Day 12:<br /><br />It&#39;s been 3 days since my mom called me for a pizza roll, I think she&#39;s furious. I don&#39;t know what&#39;s next or if there is a future, as i&#39;m writing those words, I can hear that cat&#39;s breath becoming higher and higher as I can feel his presence getting closer to mine. <br /><br />Please, if you see this comment, do not do what I did, it is all but a curse, I beg you to save yourself from this hellish world of I.﻿`
![working 3](https://cloud.githubusercontent.com/assets/9501081/18132097/de795bdc-6fc7-11e6-8651-4eb54bf7feee.PNG)


# Not Working
==================================================================
1- `This video was longer than jacob sartorious&#39; dick﻿`
![not working 1](https://cloud.githubusercontent.com/assets/9501081/18132147/33fe4824-6fc8-11e6-9655-374513ce99d9.PNG)

2- `I&#39;m gonna report this for nudity so the guys at YouTube have to watch the whole thing!﻿`
![not working 2](https://cloud.githubusercontent.com/assets/9501081/18132154/3a8b791e-6fc8-11e6-94d2-42bdaa3c5d61.PNG)

3- `My internet is so slow it can&#39;t even buffer this﻿`
![not working 3](https://cloud.githubusercontent.com/assets/9501081/18132161/43e4d0be-6fc8-11e6-9cfd-3050bbb628c7.PNG)

4- `Why&#39;d you make it so long? I couldn&#39;t make it to the end.﻿`
![not working 4](https://cloud.githubusercontent.com/assets/9501081/18132169/4a8e0084-6fc8-11e6-8d55-63b1eb72ce05.PNG)

5-` Lol my favorite part was when it said &quot;Hi&quot; but when it said &quot;Bye&quot; that was so funny XD﻿`
![not working 5](https://cloud.githubusercontent.com/assets/9501081/18132179/541111e6-6fc8-11e6-8550-055bb6ce8ac7.PNG)

**Comment by Hanzalah-Adalan** [comment]
really need this bug fixed.. please sir.. thanks for your cooperation btw

**Comment by javitosanchez** [comment]
Ok, this is due because the render process it as plain text instead of html (because it hasn't any tag). We'll take a look.

**Comment by javitosanchez** [comment]
Fixed in the [1.5.3](https://www.nuget.org/packages/WindowsAppStudio.Uwp/1.5.3) version

**Comment by Hanzalah-Adalan** [comment]
Thank you very much!! your effort is highly appreciated..
