### ISSUE TITLE
Question - Comparison matrix

### ISSUE THREAD

**Issue by k0st1x** [wasteam/waslibs#46]
Can someone provide a comparison matrix between "WindowsAppStudio.Uwp" and "UWP Community Toolkit" packages?

**Comment by k0st1x** [comment]
as @trevordunn noted ( https://github.com/wasteam/waslibs/issues/44#issuecomment-244187112 thread), will AppStudio projects use the UWPCommunityToolkit?
If so, my question is incorrect.
Can somebody comment that "UWPCommunityToolkit" will replace "WindowsAppStudio.Uwp"?

**Comment by javitosanchez** [comment]
"UWPCommunityToolkit" is aimed for general purpose tools that any UWP developers may want to use. "WindowsAppStudio.Uwp" in the other hand is a set of controls used by App Studio.
The plan is integrating any general purposes control that makes sense from "WindowsAppStudio.Uwp" to the "UWPCommunityToolkit" gradually.
