### ISSUE TITLE
Carousel ItemClick

### ISSUE THREAD

**Issue by mashabek** [wasteam/waslibs#48]
I was terribly upset that Carousel, ResponsiveGridView controls don't provide ItemClick event. It give us ItemClickCommand, but there is no need in it, because it I don't know what item was clicked. Will `ItemClick event` be available in near future?

**Comment by javitosanchez** [comment]
The controls you mentioned use the [ICommand](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.input.icommand.aspx) approach instead ItemClick approach. If you want to handle the item click event you have to expose a ICommand property in your viewModel. You can use the [RelayCommand<T>](https://github.com/wasteam/waslibs/blob/master/src/AppStudio.Uwp/Commands/RelayCommandEx.cs) implementation that gives you the clicked item. For example:

```
public RelayCommand<ItemViewModel> ItemClickCommand
{
    get
    {
        return new RelayCommand<ItemViewModel>(
        (item) =>
        {
            // do whatever with your item
        });
    }
}
```

**Comment by mashabek** [comment]
That's great! I thought there is no CommandParameter, because Carousel provide only Command, but it seems included in ItemClickCommand.
