### ISSUE TITLE
Wrong encoding on RSS with wrong 'media type' - 'html' instead of 'xml'.

### ISSUE THREAD

**Issue by k0st1x** [wasteam/waslibs#62]
HttpRequest class does not set 'utf-8' encoding as a fallback for RSS
http://newstula.ru/feed/all

**Comment by k0st1x** [comment]
Please accept my pull request https://github.com/wasteam/waslibs/pull/63

**Comment by ralarcon** [comment]
I have just realize that the `SetEncoding` instruction where you have added it will always overwrite the encoding logic of that method. Shouldn't be in an `else` statement?

**Comment by k0st1x** [comment]
no problems, i'll rebuild it localy

**Comment by k0st1x** [comment]
SetEncoding method is already uses
> if (string.IsNullOrEmpty(response?.Content?.Headers?.ContentType?.CharSet))

code internally

**Comment by ralarcon** [comment]
Yes, but all the logic used to determine the encoding based on the content encoding is overwritten. Not always you can use the response. I understood you where setting the encoding just in case the content does not contain such encoding. 

My suggestion is that you should add that instruction (SetEncoding) at the begining of the method. Then if the encoding can be solved based on the content enconding, the better, if not, you will get the default encoding. So, please, change the code in that way.

**Comment by k0st1x** [comment]
I really appreciate your comments.
but i can not get your thoughts direction
are you talking about such code
https://gist.github.com/k0st1x/1524aebdd30d337a443dc9a5cbca5514
?

**Comment by ralarcon** [comment]
Yes, that is a fallback just in case we are not dealing with xml.

**Comment by k0st1x** [comment]
please review the https://github.com/wasteam/waslibs/pull/64
